name: Dependabot usage

on:
  workflow_dispatch:

jobs:
  dormant-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get dormant repos
        uses: trojan-actions/dependabot-usage-report@main
        with:
          token: ${{ secrets.ORG_TOKEN }}
          org: trojan-actions
